{% set name = "libmfile" %}
{% set version = "r57.a18a066" %}
{% set commit = "a18a06616fcdabf6e4989f2410680f6724f44762" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ikp.uni-koeln.de/jmayer/{{ name }}/-/archive/{{ commit }}/{{ name }}-{{ commit }}.tar.gz
  sha256: a8133ea983f604151299b3819b64535dc5e096e41623755ceb0d78033438f004

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake

about:
  home: https://gitlab.ikp.uni-koeln.de/jmayer/libmfile
  license: BSD-2-Clause
  license_family: BSD
  license_file: license.md
  summary: 'Library for compressed storage of spectroscopy data in nuclear physics'
  dev_url: https://gitlab.ikp.uni-koeln.de/jmayer/libmfile
