{% set version = "2.0" %}

package:
  name: talys-suite
  version: {{ version }}

source:
  url: https://nds.iaea.org/talys/codes/talys.tar
  sha256: 3e7136a210cee958f1480351419b1c18d59efb01ba3582fd660bbd0c9fe46dc3

build:
  number: 0
  skip: True  # [win]

outputs:
  - name: talys-data
    build:
      noarch: generic
      script:
      - |
        for dir in structure samples doc misc; do
          find $dir -type f -exec install -Dm 644 "{}" "${PREFIX}/share/talys/{}" \;
        done

        # Add the post activate/deactivate scripts
        for action in activate deactivate; do
          mkdir -p "${PREFIX}/etc/conda/${action}.d"
          for suffix in sh csh fish; do
            cp "${RECIPE_DIR}/${action}.${suffix}" "${PREFIX}/etc/conda/${action}.d/${action}-talys.${suffix}"
          done
        done

  - name: talys-base
    build:
      noarch: generic
      script: 
      - |
        datapath="${PREFIX}/share/talys"
        datapathnew=$(echo "$datapath" | sed 's/\//\\\//g')
        cd 'source' || exit

        # Setup talys data directory
        sed -i "s/^  codedir = '.*'/  codedir = '${datapathnew}\/'/" machine.f90

        # Hardcoding the username does not make any sense
        # For windows, should we use USERNAME instead?
        sed -i "s/^  user = '.*'/  call getenv('USER',user)/" machine.f90

        # Paths can become quite long
        for f in *.f90 *.f; do
          sed -i 's/len=132\(.*dir\)/len=1024\1/' "$f"
          sed -i 's/len=132\(.*path\)/len=1024\1/' "$f"
          sed -i 's/len=132\(.*file\)/len=1024\1/' "$f"
        done

        FFLAGS=-Ofast
        $FC $FFLAGS -c *.f
        $FC $FFLAGS -c *.f90
        $FC $FFLAGS *.o -o talys

        install -Dm 0755 talys ${PREFIX}/bin/talys
    requirements:
      build:
        - {{ compiler('fortran') }}

  - name: talys
    build:
      script:
        - echo "Nothing to build here, just add dependencies."
    requirements:
      run:
        - {{ pin_subpackage('talys-base', exact=True) }}
        - {{ pin_subpackage('talys-data', exact=True) }}
    test:
      commands:
        - echo "projectile n\nelement Pb\nmass 208\nenergy 10.0" | talys

about:
  home: https://nds.iaea.org/talys/
  dev_url: https://github.com/arjankoning1/talys
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A nuclear reaction program'
  description: |
    TALYS is a software package for the simulation of nuclear reactions below 200 MeV. TALYS is based on state-of-art nuclear structure and reaction models.
