{% set version = "2.0" %}

package:
  name: talys-suite
  version: {{ version }}

source:
  url: https://nds.iaea.org/talys/codes/talys.tar
  sha256: 3e7136a210cee958f1480351419b1c18d59efb01ba3582fd660bbd0c9fe46dc3

build:
  number: 0
  skip: True  # [win]

outputs:
  - name: talys-data
    build:
      script:
        - build-talys-data.sh

  - name: talys-base
    build:
      script:
        - build-talys-base.sh
    requirements:
      build:
        - {{ compiler('fortran') }}

  - name: talys
    build:
      script:
        - echo "Nothing to build here, just add dependencies."
    requirements:
      run:
        - {{ pin_subpackage('talys-base', exact=True) }}
        - {{ pin_subpackage('talys-data', exact=True) }}

about:
  home: https://nds.iaea.org/talys/
  dev_url: https://github.com/arjankoning1/talys
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A nuclear reaction program'
